# Generated by Django 5.1.3 on 2025-01-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=2, max_length=10, verbose_name='senha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
    ]
